title: Kordiak Park Explorer
email: info@kordiakpark.example
description: Exploring the beauty of Kordiak Park in Columbia Heights, MN.
baseurl: "/Kordiak_Park"
url: "https://r-egun.github.io"

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Collections (for future expansion like the dog roster)
collections:
  dogs:
    output: true
